### ISSUE TITLE
Bit flag specifications are unclear

### ISSUE THREAD

**Issue by fgrape** [assaabloy-ppi/salt-channel#15]
The parts of the specification with bit flags are not as clear as they could be. In the case of M1/Header (included below for clarity) the question boils down to: Is the ServerSigKeyIncluded bit the most or least significant bit? There seems to be a roughly 50/50 split depending on who you ask. 

    **** M1/Header ****
    
    1   PacketType.
        Integer in [0, 127]
        The value is 1 for this packet.
    
    1b  ServerSigKeyIncluded.
        Set to 1 when ServerSigKey is included in the message.
        
    7b  Zero.
        Bits set to 0.

The correct answer is that the second byte of M1/Header is 1 when ServerSigKeyIncluded is set, i.e. the ServerSigKeyIncluded bit is the least significant bit. The M1/Header byte array is: [0x01, 0x01]. 

I read the message specification such in named "chunks" of variable bit length and placed each new chunk right after the previous one in a bit array, the same way you read English. Like this: [PacketType, ServerSigKeyIncluded, Zero], which of course results in the ServerSigKeyIncluded being the most significant bit of the second byte instead of the least significant bit. If you read the specification like that the correct way to place the elements into the array is [PacketType, Zero, ServerSigKeyIncluded]

I think the problem is that you forget the sentence about bit order when come back to the specification to only read a message specification to make sure that you implemented it correctly. 

Possible solution: 
* Change to specify the bit number when defining flags. 

Result:

    **** M1/Header ****
    
    1   PacketType.
        Integer in [0, 127]
        The value is 1 for this packet.
    
    bit0  ServerSigKeyIncluded.
        Set to 1 when ServerSigKey is included in the message.
        
    bit1-7  Zero.
        Bits set to 0.

Are there other better solutions to make the bit order more clear in packet specifications without making the specifications convoluted and hard to understand?

PS. According to wikipedia recommended bit numbering for RFC documents is "MSB 0", i.e. bit 0 is most significant bit. Example: [RFC1166 Internet Numbers](https://tools.ietf.org/html/rfc1166) page 1.

**Comment by franslundberg** [comment]
After talking to Felix.

"recommended bit numbering for RFC documents is "MSB 0". Yes, but they use big-endian byte-order, so it matches that. With our little-ending byte order, I think the existing little-bit or "LSB 0" bit order is better.

Also, "bit1-7"... I like it, but seems inconsistent with the byte spec. Bytes don't use indexes and range, only size. It makes it easy to specify.

Conclusion: let's sleep on it.

**Comment by franslundberg** [comment]
I change a little. Added "Bit 1-7" and such to the descriptions. Example:

    
    **** M1/Header ****
    
    1   PacketType.
        Integer in [0, 127]
        The value is 1 for this packet.
    
    1b  ServerSigKeyIncluded.
        Bit 0 is set 1 when ServerSigKey is included in the message.
        
    7b  Zero.
        Bits 1-6 are set to 0.

Also, clarified the text a bit regarding bit ordering. "LSB 0" seems like the best term for the bit order used.

**Comment by franslundberg** [comment]
Of course, the drawback with the above it that we have double-info. Not "normalized" so to say. Well, well, we just need to get it *right*. Then, it is not a problem :-)

**Comment by franslundberg** [comment]
Closing this, updated spec should be easier to understand.
