### ISSUE TITLE
SaltServerSession and multiple sequential Salt Channel sessions

### ISSUE THREAD

**Issue by fgrape** [assaabloy-ppi/salt-channel#16]
According to [the specification](https://github.com/assaabloy-ppi/salt-channel/blob/master/files/spec/salt-channel-v2-draft8.md#session-close):

> "The underlying reliable channel MAY be reused for multiple sequential Salt Channel sessions."

It seems like SaltServerSession does **not** support this. I have tested the following with /salt-channel/src-x/saltchannelx/ws/**WsTestServer**.java with results as described:

1. Execute A1A2 session. Then try to execute a handshake.
2. Execute A1A2 session. Then try to execute A1A2 session again

**Result**: SaltServerSession throws: **IllegalStateException**: session is done, no application channel available

3. Execute handshake and close session. Then try to execute handshake.
4. Execute handshake and close session. Then try to execute A1A2 session

**Result**: Message arrives at test server but nothing happens. Neither A2 nor M2 is sent

**Comment by fgrape** [comment]
Update of specification clarifies this issue in [this commit](https://github.com/assaabloy-ppi/salt-channel/commit/8823f624c7ce732c1513054f7830e12789cd9615#diff-00a63c0ec77d893c8ef2c09c26fb7fb0)

**Comment by franslundberg** [comment]
To do: server should close the TCP connection (the WebSocket connection) when Salt Channel session is done.

**Comment by franslundberg** [comment]
Closing this. Fixed, I think. The test code is not really tested, however.
