### ISSUE TITLE
Minor issue in ExampleSession2.java

### ISSUE THREAD

**Issue by ppmag** [assaabloy-ppi/salt-channel#17]
Looks like 'pubkey' member is not used and is confusing here:

https://github.com/assaabloy-ppi/salt-channel/blob/master/src/saltchannel/dev/ExampleSession2.java#L26
```Java
   private static final byte[] pubkey = new byte[32];
    static {
        for (int i = 0; i < pubkey.length; i++) {
            pubkey[i] = 0x09;
        }
    }
```

**Comment by franslundberg** [comment]
Fixed, thanks for the report.
